<FirstScreen>:
    GridLayout:
        cols: 1
        padding: 10
        spacing: 10 
        Image:
            id: img
            size_hint_y: 0.8
        TextInput:
            size_hint_y: 0.1
            id: user_query
        Button:
            text: 'Search Image'
            size_hint_y: 0.3
            on_press: root.set_image()
<RootWidget>
    FirstScreen:
        id: first_screen
        name: 'first_screen'